// <auto-generated />
#nullable enable

namespace Backgrounder.Sample
{
    /// <summary>
    /// Extension methods for Backgrounder
    /// </summary>
    public static partial class SampleJobDoWorkExtensions
    {
        /// <summary>
        /// Enqueue the method Backgrounder.Sample.SampleJob.DoWork(int?) for execution in the background
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Backgrounder.Generators", "0.0.0-alpha.0.2+bd7d502a08128476d16cb35a64835892843c015c")]
        public static async global::System.Threading.Tasks.Task DoWork(this global::Backgrounder.IBackgrounder backgrounder, int? jobId)
        {
            var parameterTuple = new DoWorkMessage3299E5EA(jobId);
            await backgrounder.EnqueueAsync("Backgrounder.Sample.SampleJob.DoWork(int?)", parameterTuple);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Backgrounder.Generators", "0.0.0-alpha.0.2+bd7d502a08128476d16cb35a64835892843c015c")]
        internal static async global::System.Threading.Tasks.Task ExecuteDoWork3299E5EA(global::System.IServiceProvider serviceProvider, byte[] messageBody)
        {
            var messageSerializer = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Backgrounder.IMessageSerializer>(serviceProvider);
            var methodParameters = messageSerializer.Deserialize<DoWorkMessage3299E5EA>(messageBody);
            var worker = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<SampleJob>(serviceProvider);
            await worker.DoWork(methodParameters.jobId);
        }

        [global::System.Runtime.CompilerServices.ModuleInitializerAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Backgrounder.Generators", "0.0.0-alpha.0.2+bd7d502a08128476d16cb35a64835892843c015c")]
        internal static void RegisterDoWork3299E5EA()
        {
            BackgroundRouter.Register("Backgrounder.Sample.SampleJob.DoWork(int?)", Backgrounder.Sample.SampleJobDoWorkExtensions.ExecuteDoWork3299E5EA);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Backgrounder.Generators", "0.0.0-alpha.0.2+bd7d502a08128476d16cb35a64835892843c015c")]
        public record DoWorkMessage3299E5EA(int? jobId);
    }
}
